sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:

matrix:
  allow_failures:
    - d: ldc

addons:
  apt:
    packages:
      - libcairo2-dev
      - libpng-dev
      - libopenblas-dev

script:
  - dub test --build=unittest-cov
  - |
    if [ $DC = dmd ]; then
      make doc
    fi

after_success:
 - bash <(curl -s https://codecov.io/bash)

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: generated-docs
  on:
    branch: master
    condition: $DC = dmd
