version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-dmd
      - test-ldc
jobs:
  test-dmd:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: apt
          command: sudo apt-get install libopenblas-dev libcairo2-dev
      - run:
          name: test
          command: |
            source "$(curl -fsS  --retry 3 https://dlang.org/install.sh | bash -s dmd --activate)"
            $DC --version
            dub test -b=unittest-cov
            bash <(curl -s https://codecov.io/bash)
  test-ldc:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: apt
          command: sudo apt-get install libopenblas-dev libcairo2-dev
      - run:
          name: test
          command: |
            source "$(curl -fsS  --retry 3 https://dlang.org/install.sh | bash -s ldc --activate)"
            $DC --version
            dub test -b=unittest-cov
            bash <(curl -s https://codecov.io/bash)
